### ISSUE TITLE
Idea: Strip + UPX optional commands

### ISSUE THREAD

**Issue by juancarlospaco** [kaushalmodi/nim_config#1]
What do you think of the idea of adding a command to run:

- [x] Implement an optional command to run `strip -s` on binary output files, `nim strip file` ?.
- [x] Implement an optional command to run `upx --ultra-brute` on binary output files, `nim upx file` ?.

I will combine this with [pre-commit Nim plugin](https://github.com/juancarlospaco/pre-commit-nim#pre-commit-nim) and [crosscompiler package](https://github.com/juancarlospaco/nim-crosscompile#nim-crosscompile)
Awesome project, keep it up :grey_exclamation: 
:cat:

**Comment by kaushalmodi** [comment]
Now `nim strip file` and `nim upx file` work too!

**Comment by kaushalmodi** [comment]
@juancarlospaco It would be cool to get your cross compiler proc recipe as a NimScript task, that works on Travis too. Would you like to contribute that to this project?

**Comment by juancarlospaco** [comment]
I need it as dependency to install with nimble, because I am copy-pasting the same exact code on several projects like [Nim-Telegram-Bot](https://github.com/juancarlospaco/nim-telegram-bot#nim-telegram-bot) and [HackPad](https://github.com/juancarlospaco/nim-hackpad#nim-hackpad), so I dont think I will take it down.

Having said that, I agree that your idea is nice, we can port it to NimScript too, feel free to steal the code, let me know of the progress.

[Check the new GitHub Actions thingy too.](https://twitter.com/github/status/1052248654445076481)

Is awesome to see cool projects on NimScript, because there are not a lot of them.
:smile_cat:
