### ISSUE TITLE
sstrip support

### ISSUE THREAD

**Issue by juancarlospaco** [kaushalmodi/nim_config#16]
Theres a strip that strips more than `strip`, is named `sstrip`, 
seems easy to install, is a single file pure C file, been trying it for some time now, 
it fully removes the Headers of binaries, while still being completely correct binary, 
no observable downside, even the Linux command `file` sees the binary as not having Headers.

https://github.com/BR903/ELFkickers/tree/master/sstrip

Use:
```console
sstrip binary
```

Would be cool to have a Task to install `sstrip` and use it along vanilla `strip`.
I dont do this because I kinda sux at install Tasks. I manually git cloned and run the makefile.
:slightly_smiling_face:

**Comment by kaushalmodi** [comment]
I haven't used `sstrip`, and also I see that it hasn't been updated in 6 years. So I am not quite sure if this should be a part of this repo. What is the size optimization when using sstrip vs strip?

**Comment by kaushalmodi** [comment]
Just pasting something here on what I find on sstrip vs strip as I do not understand the technical merits of sstrip: 

- http://lists.en.qi-hardware.com/pipermail/discussion/2011-January/006709.html

**Comment by juancarlospaco** [comment]
Ohh, Ok. :+1: 
I did not know about that link.
