### ISSUE TITLE
Compile, run and discard output file

### ISSUE THREAD

**Issue by ghost** [kaushalmodi/nim_config#18]
If I use `nim runc`:

https://github.com/kaushalmodi/nim_config/blob/bda6f591a0cdd1ff2f158882a31dcc921eb103ba/config.nims#L385-L390

it appears that an output file would still be created in current directory
(or in `--out` or `--outdir`), while `go run` puts any file in temporary
directory (as far as I know).

**Comment by kaushalmodi** [comment]
You can set the outdir to be the temp dir.

**Comment by ghost** [comment]
This seems to do the trick:

~~~nim
# %APPDATA%\nim\config.nims
import os
task run, "run":
   setCommand("compile")
   switch("run")
   switch("outdir", getTempDir())
~~~

**Comment by kaushalmodi** [comment]
Yep, that's exactly what I meant. NimScript is very configurable. You can make your runc task set all the switches you prefer.

**Comment by cup** [comment]
https://github.com/nim-lang/Nim/issues/12940
